import { StyleSheet } from 'react-native'
import { Colors, Metrics } from '../../Themes'

export default StyleSheet.create({
  content:{
    paddingTop:30,
    backgroundColor:'#000',
    flexDirection:'column'
  },
  topSearch:{
    flexDirection:'row',
    justifyContent:'space-between',
    paddingRight:20,
    height:45
  },
  backHistory:{
    width:30,
    marginRight:10,
    marginLeft:5,
    marginTop:5,
    height:30
  },
  searchInput:{
    flex:1,
    height:30,
    borderWidth:1,
    borderColor:"green",
    backgroundColor:'#fff'
  },
  historyList:{
    flex:1,
    backgroundColor:'#efefef'
  },
  goodsList:{
    flex:1,
    padding:3,
    backgroundColor:'#fff'
  },
  //热搜
  hotSearchContent:{
    padding:10,
    backgroundColor:'#fff',
    marginBottom:10
  },
  historyTitle:{
    fontWeight:'bold',
    fontSize:16,
    height:40,
    lineHeight:30,
    color:'#101010'
  },
  eachHotView:{
    borderRadius:2,
    backgroundColor:'#e3e3e3',
    paddingHorizontal:15,
    height:25,
    marginRight:5
  },
  eachHot:{
    lineHeight:25,
  },
  borderB:{
    borderBottomWidth:1,
    borderBottomColor:"#eee",
    borderStyle:'solid'
  },
  eachHistory:{
    height:40,
    lineHeight:40
  },
  deleteContent:{
    justifyContent:'center',
    flexDirection:'row',
    marginTop:20
  },
  deleteSubContent:{
    flexDirection:'row',
    width:300,
    height:40,
    alignItems:'center',
    justifyContent:'center',
    borderColor:'#aaa',
    borderWidth:1
  },
  deleteText:{
    marginLeft:5
  },
  trash:{
    color:"#555"
  },
  noDataView:{
    flexDirection:'row',
    justifyContent:'center',
  },
  noData:{
    paddingTop:40,
    alignItems:'center',
    fontSize:14,
    color:"#aaa"
  },
  goodsIcon:{
    height:200
  },
  goodsName:{
    fontSize:14,
    paddingVertical:10,
    paddingLeft:10
  }
  ,
  navButtonLeft: {
    marginLeft: Metrics.baseMargin,
    backgroundColor: Colors.transparent,
    width: Metrics.icons.small
  },
  eachGoodsRow:{
    flexDirection:'row',
  },
  leftGood:{
    flex:1,
    marginRight:5
  },
  rightGood:{
    flex:1
  }
})
