import { StyleSheet } from 'react-native'
import { Colors, Metrics } from '../../Themes'

export default StyleSheet.create({
  container:{
    paddingTop:65,
    backgroundColor:"#eee"
  },
  orderNumber:{
    lineHeight:40,
    paddingLeft:10,
    backgroundColor:"#fff"
  },
  listContent:{
    backgroundColor:"#fff",
    marginTop:10,
    paddingLeft:20,
    paddingTop:20
  },
  eachContent:{
    position:'relative',
    height:100,
    borderLeftWidth:1.5,
    borderColor:"#ddd",
  },
  location:{
    width:20,
    height:20,
    position:'absolute',
    left:-10,
    top:0,
    zIndex:1
  },
  locationB:{
    width:30,
    height:30,
    position:'absolute',
    left:-15,
    top:0,
    zIndex:1
  },
  infoContent:{
    paddingLeft:20,
    height:85
  },
  infoInnerContent:{
    height:85,
    borderColor:"#ddd",
    borderBottomWidth:0.5
  },
  infoTop:{
    color:"#555",
    fontSize:14,
    lineHeight:20,
  },
  infoTopHeight:{
    height:50
  },
  endText:{
    color:'green'
  },
  infoTime:{
    fontSize:12
  },
  payBtnContent:{
    paddingHorizontal:10,
    paddingVertical:20
  },
  btnInner:{
    backgroundColor:Colors.error,
    flexDirection:'row',
    justifyContent:'center',
    alignItems:'center',
    height:40
  },
  linkImg:{
    width:20,
    height:20
  },
  payText:{
    color:Colors.snow
  }
})
